"""add aidols and companions tables

Revision ID: 90b1f178f8df
Revises: 
Create Date: 2026-01-22 08:28:05.859816

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90b1f178f8df"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aidols",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("concept", sa.String(), nullable=True),
        sa.Column("profile_image_url", sa.String(), nullable=False),
        sa.Column("claim_token", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aidols")),
    )
    op.create_table(
        "companions",
        sa.Column("aidol_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("biography", sa.Text(), nullable=True),
        sa.Column("profile_picture_url", sa.String(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["aidol_id"], ["aidols.id"], name=op.f("fk_companions_aidol_id_aidols")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companions")),
    )
    with op.batch_alter_table("companions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_companions_aidol_id"), ["aidol_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("companions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companions_aidol_id"))

    op.drop_table("companions")
    op.drop_table("aidols")
    # ### end Alembic commands ###
